version: '3'

volumes:
  mysql-volume:

services:
  web:
    image: nginx:latest 
    container_name: web
    depends_on:
      - vue
      - api
    tty: true
    ports:
      - 80:80 
    volumes:
      - ./vue:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  vue:
    build: ./docker/vue
    container_name: vue
    volumes:
      - ./vue:/app/vue
    tty: true
    working_dir: /app/vue

  api:
    container_name: api
    build: ./docker/api
    depends_on:
      - db
    volumes:
      - ./api:/var/www/api

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: samurai
      MYSQL_PASSWORD: nobunaga
    ports:
      - 3306:3306
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
